### ISSUE TITLE
cms not auto generated, but hand coded

### ISSUE THREAD

**Issue by Morriz** [sarkistlt/graphql-auto-generating-cms#11]
What are you selling us? I see that the frontend app is not generated at all from the `/graphql_cms_endpoint` endpoint. I do notice a lot of manual coding in your example frontend app though. This seems like a hoax, or I am overlooking where the generation phase takes place.

Please show with documentation how to generate the frontend from the endpoint's json.

**Comment by sarkistlt** [comment]
I'm not selling anything. Just trying to help and save time of other developers, at least on development stage. I do it at my free time, I'm not getting payed for it. So phrase "selling us" sounds incorrect.

And this module does it's job, I'm using it on all project's on development stage, it saves a Lot of time. It's not worldPress or jomla so you shouldn't expect a lot from this module. But working on GrpahQL API and with no time waisting be able to edit content, add/see your data, that's pretty good.

90% of front end I built in a week so it's not perfectly well written code, but that wasn't my purpose. My purpose was wile I'm working on graphQL API with tens of types, create something to help me manage content without direct manipulations in db and test API.

And yes it's generating front end from  `/graphql_cms_endpoint` and [here](https://github.com/sarkistlt/graphql-auto-generating-cms/blob/master/src/index.jsx), where json became to UI.

And again, there are a lot to improve and I have a lot ideas how to make this module better, but as I said, I'm doing it at my free time, for Free. So if you have any suggestions you are welcome to contribute.

**Comment by Morriz** [comment]
Tnx for the reply. I was investing quite some time in this only to realise that this package does not use the server side resolver+schema information. I see that you coded (copy/pasted and modded?) them by hand for the client. What exactly is 'automated' if I may ask? Html on the screen for that list of actions that your endpoint matches? Why not consume the /graphql endpoint directly in the client and inspect it there? Get rid of that middleware as it is not needed at all imo. Also, you don't have to enforce those weird naming conventions for your api. I already modded it to use camelcased method names like `createActivity` instead of `activity_create`.

Anyways, of course I'd like to see this going to something that really makes sense. I've made my observations and hope it helps. I would target using the server code for client code generation first, as that is a lot of work now. That should definitely be automated.

Thanks for sharing your code!

**Comment by sarkistlt** [comment]
it's nice idea to use just `/graphql` but I didn't found any easy way to get all query and mutations methods directly through endpoint. We need 'weird' naming just to simplify code parsing on middleware, there are no problem to use camelcased, but I did it for purpose to logically separate method name and action identification. Without naming pattern it's almost impossible to automatically parse API methods and connections between them.
