### ISSUE TITLE
Cannot run the example on the Windows machine

### ISSUE THREAD

**Issue by maxceem** [sarkistlt/graphql-auto-generating-cms#3]
Hi.

Thank you for the project it looks interesting. 
But when I try the example I've got an error when performing `npm i`:
```
> graphql-auto-generating-cms@2.2.61 build e:\dev_temp\graphql-auto-generating-cms
> NODE_ENV=test gulp

"NODE_ENV" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
```

I think this could be solved by using something like https://www.npmjs.com/package/cross-env

**Comment by sarkistlt** [comment]
Hi, that because on windows you should use ```set NODE_ENV``` instead of just ```NODE_ENV```, so basically open package.json in any text editor and change ```NODE_ENV=test gulp``` to ```set NODE_ENV=test gulp``` and all other scripts where I use ```NODE_ENV``` if you need to.

**Comment by maxceem** [comment]
I've run it under the linux instead, though I knew about `set`. Mainly I've posted an issue just in case you would like to make it flawless to run for new window users.

**Comment by honarpour** [comment]
@sarkistlt Hey. I changed "NODE_ENV" to "SET NODE_ENV" but still can't run the examples. Also can't run the project itself. I don't get any errors but it just exits after I run "npm run example" or any other script.

![image](https://cloud.githubusercontent.com/assets/4552454/23137279/1fc8a686-f76f-11e6-93d5-3b2f9c8c1f67.png)

**Comment by sarkistlt** [comment]
Hi, can you please update from muster branch (I've just added cross-env support) and follow to [this instruction](https://github.com/sarkistlt/graphql-auto-generating-cms/tree/master/example):

1. ```git clone https://github.com/sarkistlt/graphql-auto-generating-cms.git```

2. ```cd graphql-auto-generating-cms```

2. ```npm i```

3. ```npm run-script example```

4. open ```http://localhost:7700/``` in your browser

**Comment by honarpour** [comment]
Worked, thanks.
