### ISSUE TITLE
Build an online Demo?

### ISSUE THREAD

**Issue by subodhpareek18** [sarkistlt/graphql-auto-generating-cms#6]
There are some public graphql apis available, something like https://github.com/graphql/swapi-graphql

Is there a way a working online demo can be built, which lets us try out the UI before setting it up on a machine.

Thank you

**Comment by sarkistlt** [comment]
sure, http://web4fly.com:7700/

**Comment by Morriz** [comment]
The demo does not go past the loading stage in latest Safari ;(

**Comment by sarkistlt** [comment]
Fixed, just try one more time.

**Comment by Morriz** [comment]
not yet, see screenie:
<img width="1269" alt="screen shot 2017-02-26 at 1 11 53 pm" src="https://cloud.githubusercontent.com/assets/941865/23343223/42881f2a-fc25-11e6-8b11-630840a9e58b.png">

**Comment by sarkistlt** [comment]
is it on demo page or on your local example? this is how demo looks in safari.
<img width="1326" alt="screen shot 2017-02-26 at 12 52 56 pm" src="https://cloud.githubusercontent.com/assets/5773343/23343576/a551b4b6-fc22-11e6-9f1f-9b893fc0bc07.png">

It works even on mobile browsers

**Comment by Morriz** [comment]
I just opened your link at http://web4fly.com:7700/ <http://web4fly.com:7700/>, and have that problem in mobile view as you can see...
